version: '3'

services:
  proxy:
    image: proxygx-nginx
    build:
      context: .
    ports:
      - "9999:80"
    depends_on:
      - apigx01
    networks:
      - proxygx-network
  
  apigx01:
    image: mkshimao/handsoncloudgx
    ports:
      - "20001:80"
    networks:
      - proxygx-network
  

networks: 
    proxygx-network:
      driver: bridge